#******************************************************************************
#
# Configuration file for create_cust_image_blob.py
#
# Apollo4P Blue KXR EVB / Zephyr peripheral_hr
#
#******************************************************************************
[Settings]
ambiq_owned = 0x0
chip = apollo4l
app_file = starter_binary_apollo4_blue.bin
load_address = 0x18000
enc_algo = 0x0
auth_algo = 0x0
auth_key = 0x2
kek_index = 0x80
image_type = firmware
ota = 0x0
offset = 0x0
certificate = None
output = temp_binary_apollo4_blue.bin
key_table = keys.ini
loglevel = 0x2
